# Salt used by Argon2id key derivation function.
# Change this value before deploying to production.
# Recommended: use a long, random, unique string (min 16 chars).
crypto.salt=KbjH3E9PvX7YmBMseSUsKMnIl9U8djZT/2f7LYfZU6I=
